//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 02:39:17 PM IST 
//


package models;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for file complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="file">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Country_Markets" type="{}Country_Markets" minOccurs="0"/>
 *         &lt;element name="Distributors" type="{}Distributors" minOccurs="0"/>
 *         &lt;element name="EAN_UPCS" type="{}EAN_UPCS" minOccurs="0"/>
 *         &lt;element name="M_Prod_ID" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Supplier_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Supplier_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="Product_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Updated" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Date_Added" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Quality" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Supplier_id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Prod_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Catid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="On_Market" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Stock" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Model_Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Product_View" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="HighPic" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HighPicSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="HighPicWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="HighPicHeight" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "file", propOrder = {
    "countryMarkets",
    "distributors",
    "eanupcs",
    "mProdID"
})
@XmlRootElement
public class File {

    @XmlElement(name = "Country_Markets")
    protected CountryMarkets countryMarkets;
    @XmlElement(name = "Distributors")
    protected Distributors distributors;
    @XmlElement(name = "EAN_UPCS")
    protected EANUPCS eanupcs;
    @XmlElement(name = "M_Prod_ID")
    protected List<MProdID> mProdID;
    @XmlAttribute(name = "path", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String path;
    @XmlAttribute(name = "Product_ID", required = true)
    protected BigInteger productID;
    @XmlAttribute(name = "Updated", required = true)
    protected String updated;
    @XmlAttribute(name = "Date_Added")
    protected String dateAdded;
    @XmlAttribute(name = "Quality", required = true)
    protected String quality;
    @XmlAttribute(name = "Supplier_id", required = true)
    protected BigInteger supplierId;
    @XmlAttribute(name = "Prod_ID", required = true)
    protected String prodID;
    @XmlAttribute(name = "Catid", required = true)
    protected BigInteger catid;
    @XmlAttribute(name = "On_Market", required = true)
    protected boolean onMarket;
    @XmlAttribute(name = "Stock")
    protected BigInteger stock;
    @XmlAttribute(name = "Model_Name", required = true)
    protected String modelName;
    @XmlAttribute(name = "Product_View", required = true)
    protected BigInteger productView;
    @XmlAttribute(name = "HighPic")
    protected String highPic;
    @XmlAttribute(name = "HighPicSize")
    protected BigInteger highPicSize;
    @XmlAttribute(name = "HighPicWidth")
    protected BigInteger highPicWidth;
    @XmlAttribute(name = "HighPicHeight")
    protected BigInteger highPicHeight;

    /**
     * Gets the value of the countryMarkets property.
     * 
     * @return
     *     possible object is
     *     {@link CountryMarkets }
     *     
     */
    public CountryMarkets getCountryMarkets() {
        return countryMarkets;
    }

    /**
     * Sets the value of the countryMarkets property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryMarkets }
     *     
     */
    public void setCountryMarkets(CountryMarkets value) {
        this.countryMarkets = value;
    }

    /**
     * Gets the value of the distributors property.
     * 
     * @return
     *     possible object is
     *     {@link Distributors }
     *     
     */
    public Distributors getDistributors() {
        return distributors;
    }

    /**
     * Sets the value of the distributors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distributors }
     *     
     */
    public void setDistributors(Distributors value) {
        this.distributors = value;
    }

    /**
     * Gets the value of the eanupcs property.
     * 
     * @return
     *     possible object is
     *     {@link EANUPCS }
     *     
     */
    public EANUPCS getEANUPCS() {
        return eanupcs;
    }

    /**
     * Sets the value of the eanupcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EANUPCS }
     *     
     */
    public void setEANUPCS(EANUPCS value) {
        this.eanupcs = value;
    }

    /**
     * Gets the value of the mProdID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mProdID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMProdID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link models.File.MProdID }
     * 
     * 
     */
    public List<MProdID> getMProdID() {
        if (mProdID == null) {
            mProdID = new ArrayList<MProdID>();
        }
        return this.mProdID;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setProductID(BigInteger value) {
        this.productID = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdated(String value) {
        this.updated = value;
    }

    /**
     * Gets the value of the dateAdded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateAdded() {
        return dateAdded;
    }

    /**
     * Sets the value of the dateAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateAdded(String value) {
        this.dateAdded = value;
    }

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuality() {
        return quality;
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuality(String value) {
        this.quality = value;
    }

    /**
     * Gets the value of the supplierId property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getSupplierId() {
        return supplierId;
    }

    /**
     * Sets the value of the supplierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setSupplierId(BigInteger value) {
        this.supplierId = value;
    }

    /**
     * Gets the value of the prodID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdID() {
        return prodID;
    }

    /**
     * Sets the value of the prodID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdID(String value) {
        this.prodID = value;
    }

    /**
     * Gets the value of the catid property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getCatid() {
        return catid;
    }

    /**
     * Sets the value of the catid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setCatid(BigInteger value) {
        this.catid = value;
    }

    /**
     * Gets the value of the onMarket property.
     * 
     */
    public boolean isOnMarket() {
        return onMarket;
    }

    /**
     * Sets the value of the onMarket property.
     * 
     */
    public void setOnMarket(boolean value) {
        this.onMarket = value;
    }

    /**
     * Gets the value of the stock property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getStock() {
        return stock;
    }

    /**
     * Sets the value of the stock property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setStock(BigInteger value) {
        this.stock = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the productView property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getProductView() {
        return productView;
    }

    /**
     * Sets the value of the productView property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setProductView(BigInteger value) {
        this.productView = value;
    }

    /**
     * Gets the value of the highPic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighPic() {
        return highPic;
    }

    /**
     * Sets the value of the highPic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighPic(String value) {
        this.highPic = value;
    }

    /**
     * Gets the value of the highPicSize property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getHighPicSize() {
        return highPicSize;
    }

    /**
     * Sets the value of the highPicSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setHighPicSize(BigInteger value) {
        this.highPicSize = value;
    }

    /**
     * Gets the value of the highPicWidth property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getHighPicWidth() {
        return highPicWidth;
    }

    /**
     * Sets the value of the highPicWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setHighPicWidth(BigInteger value) {
        this.highPicWidth = value;
    }

    /**
     * Gets the value of the highPicHeight property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getHighPicHeight() {
        return highPicHeight;
    }

    /**
     * Sets the value of the highPicHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setHighPicHeight(BigInteger value) {
        this.highPicHeight = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Supplier_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Supplier_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MProdID {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Supplier_id")
        protected String supplierId;
        @XmlAttribute(name = "Supplier_name")
        protected String supplierName;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the supplierId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplierId() {
            return supplierId;
        }

        /**
         * Sets the value of the supplierId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplierId(String value) {
            this.supplierId = value;
        }

        /**
         * Gets the value of the supplierName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplierName() {
            return supplierName;
        }

        /**
         * Sets the value of the supplierName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplierName(String value) {
            this.supplierName = value;
        }

    }

}
